# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-theme-minimal

title: Junteng Liu
name: Junteng Liu
description: Personal homepage of Junteng Liu, first-year PhD candidate at HKUST NLP Group.
author: Junteng Liu
bio: "First-year PhD candidate at HKUST NLP Group. Research: NLP & ML, LLM Reasoning & RL, VLM Hallucination, LLM Truthfulness & Interpretability."
email: jliugi@connect.ust.hk
avatar: ""

# URL / Name of your github repository
# Use this for github pages deployment
url: https://hirosmine.github.io
baseurl: /LJT-Homepage
repository: hirosmine/LJT-Homepage

# For a simple website, the navigation and the footer can be customized here.
navigation:
  - title: About
    url: /
  - title: Publications
    url: /publications/

# The footer is an array of items with title and url.
footer:
  - title: GitHub
    url: https://github.com/Vicent0205
  - title: Google Scholar
    url: https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
  - title: X
    url: https://x.com/junteng88716710
  - title: Source
    url: https://github.com/hirosmine/LJT-Homepage

# Google Analytics
# google_analytics: G-XXXXXXXXXX

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults for collections
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "single"
      read_time: false
      share: false

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Hong_Kong

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# _config.yml ends here
